### PR TITLE
Feature/frontend vite build

### PR DESCRIPTION
**Pull request by j4qfrost**
We were not leveraging the vite build feature for prod builds, so production was running at the same speeds as dev. This compiles the frontend into a single js file for the entire up and serves the content over nginx. There are further optimizations possible, but for now, the vite bundler is sufficiently performant.

### CODE REVIEW

**Review by pwdel — CHANGES_REQUESTED** [review]
I'm not sure if npm is necessary or not, but if not requesting a multi-stage build.

**Comment by j4qfrost** [comment]
> I'm not sure if npm is necessary or not, but if not requesting a multi-stage build.

The way I have the prod image set up, npm is already excluded from the resulting image.

**Comment by pwdel** [comment]
As far as I am concerned, you could bypass the approval to merge this. Sorry, hope I'm not holding things up here. I saw your response.

**Review by pwdel — APPROVED** [review]

**Comment by j4qfrost** [comment]
Not at all, this isn't a blocker, just a QoL change and I would rather discuss it than just push forward.

**Pull request merged**
